import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import QueryProvider from "@/layouts/QueryProvicer";
import {Toaster} from "sonner";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className="flex flex-row w-full bg-background">
        <div className="overflow-hidden w-full h-screen">
            <QueryProvider>
                <Toaster/>
                {children}
            </QueryProvider>
        </div>
        </body>

        </html>
    );
}
