interface ActivityListType {
    parent: string,
    no: string,
    row: string,
    noEntry?: boolean,
    exam_activity_type?: number,
    bill_sector?: number
}

export const activityList: ActivityListType[] = [
    {
        parent: '1',
        no: '1',
        exam_activity_type: 1,
        row: 'প্রশ্নপত্র প্রণয়ন',
        noEntry: true,
    },
    {
        parent: '1',
        no: '1.1',
        row: 'তত্ত্বীয় কোর্স',
        exam_activity_type: 1,
        bill_sector: 10,
    },
    {
        parent: '1',
        no: '1.2',
        row: 'ব্যবহারিক কোর্স',
        exam_activity_type: 1,
        bill_sector: 3,
    },
    {
        parent: '1',
        no: '1.3',
        row: 'টিউটোরিয়াল',
        exam_activity_type: 1,
        bill_sector: 2,
    },
    {
        parent: '1',
        no: '1.4',
        exam_activity_type: 1,
        row: 'টার্মিনাল',
        bill_sector: 20,
    },
    {
        parent: '2',
        row: 'প্রশ্নপত্র সমীক্ষণ (মডারেশন)',
        no: '2',
        exam_activity_type: 3,
        bill_sector: 8,
    },
    {
        parent: '3',
        row: 'প্রশ্নপত্র অনুবাদ',
        exam_activity_type: 2,
        bill_sector: 1,
        no: '3',
    },
    {
        parent: '4',
        row: 'প্রশ্নপত্র লিখন',
        exam_activity_type: 10,
        no: '4',
    },
    {
        parent: '5',
        row: 'প্রশ্নপত্র ফটোকপি',
        exam_activity_type: 11,
        no: '5',
    },
    {
        parent: '6',
        row: 'উত্তরপত্র পরীক্ষণ',
        no: '6',
        exam_activity_type: 4,
        noEntry: true,
    },
    {
        parent: '6',
        row: 'তত্ত্বীয় কোর্স',
        exam_activity_type: 4,
        bill_sector: 1,
        no: '6.1',
    },
    {
        parent: '6',
        row: 'ব্যবহারিক কোর্স',
        exam_activity_type: 4,
        bill_sector: 3,
        no: '6.2',
    },
    {
        parent: '6',
        row: 'টিউটোরিয়াল',
        exam_activity_type: 4,
        bill_sector: 2,
        no: '6.3',
    },
    {
        parent: '6',
        row: 'টার্মিনাল',
        exam_activity_type: 4,
        bill_sector: 20,
        no: '6.4',
    },
    {
        parent: '6',
        row: 'প্রেজেন্টেশান',
        exam_activity_type: 4,
        bill_sector: -1,
        no: '6.5',
    },
    {
        parent: '6',
        row: '৩য় পরীক্ষণ / স্ক্রুটিনী',
        exam_activity_type: 4,
        bill_sector: 4,
        no: '6.6',
    },
    {
        parent: '7',
        row: 'মৌখিক পরীক্ষা',
        exam_activity_type: 7,
        no: '7',
    },
    {
        parent: '8',
        row: 'পরীক্ষক',
        exam_activity_type: 7,
        no: '8',
        noEntry: true,
    },
    {
        parent: '8',
        row: 'ফিল্ড ওয়ার্ক/ইন্ডাস্ট্রিয়াল ট্যুর',
        exam_activity_type: 7,
        bill_sector: 5,
        no: '8.1',
    },
    {
        parent: '8',
        row: 'ব্যবহারিক নোট বুক',
        exam_activity_type: 7,
        bill_sector: 7,
        no: '8.2',
    },
    {
        parent: '8',
        row: 'সংগৃহীত নমুনা পরীক্ষণ',
        no: '8.3',
    },
    {
        parent: '8',
        row: 'প্রজেক্ট/টার্ম পেপার/ইন্টার্নশিপ রিপোর্ট ',
        no: '8.4',
        exam_activity_type: 7,
        bill_sector: 21
    },
    {
        parent: '8',
        row: 'থিসিস (মাস্টার্স/এম.ফিল/পিএইচ.ডি)',
        exam_activity_type: 7,
        bill_sector: 21,
        no: '8.5',
    },
    {
        parent: '9',
        row: 'ব্যবহারিক পরীক্ষার সম্মানী',
        exam_activity_type: 5,
        bill_sector: 3,
        no: '9',
    },
    {
        parent: '10',
        row: 'টেবুলেশন',
        exam_activity_type: 9,
        no: '10',
    },
    {
        parent: '11',
        row: 'গ্রেডসিট লিখন',
        exam_activity_type: 12,
        no: '11',
    },
    {
        parent: '12',
        row: 'গ্রেডসিট যাচাইকরণ',
        exam_activity_type: 13,
        no: '12',
    },
    {
        parent: '13',
        row: 'থিসিস গাইড/সুপারভিশন',
        exam_activity_type: 8,
        no: '13',
    },
    {
        parent: '14',
        row: 'সভাপতির সম্মানী ভাতা',
        exam_activity_type: 14,
        no: '14',
    },
    {
        parent: '15',
        row: 'পরীক্ষা কমিটির সদস্য সম্মানী',
        exam_activity_type: 15,
        no: '15',
    },
    {
        parent: '16',
        row: 'পরিদর্শক সম্মানী (প্রতি টিউটোরিয়াল)',
        exam_activity_type: 16,
        no: '16',
    },
    {
        parent: '17',
        row: 'ইনসিডেন্টাল চার্জ (সংযুক্ত ভাউচার নং- )',
        no: '17',
    },
];

export default activityList;
